document.writeln("<!doctype html>");
document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("	<meta charset=\"UTF-8\">");
document.writeln("	<meta name=\"viewport\" content=\"initial-scale=1.0, maximum-scale=1.0, user-scalable=no\"/>");
document.writeln("	<title>En-footet</title>");
document.writeln("	<link rel=\"stylesheet\" href=\"../css/index.css\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	<div id=\"bottom-banner\" class=\"bottom-banner en-bottonbanner\">");
document.writeln("	</div>");
document.writeln("	<footer id=\"footer\">");
document.writeln("		<div id=\"footer-top\" class=\"EN-footer-top\">");
document.writeln("			<div id=\"footer-top-logoo\">");
document.writeln("				<a href=\"EN-index.html\"><img src=\"../images/newlogo.png\" alt=\"\"></a>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\"\"><img src=\"../images/wachat2new.png\" alt=\"\"></a></li>");
document.writeln("					<li><a href=\"https://twitter.com/GvrcJameszhao\"><img src=\"../images/twwiter2.png\" alt=\"\"></a></li>");
document.writeln("					<li><a href=\"https://www.facebook.com/gvrcshanghai/\"><img src=\"../images/facebook-hover.png\" alt=\"\"></a></li>");
document.writeln("				</ul>");
document.writeln("				<span class=\"EN-line\"></span>");
document.writeln("			</div>");
document.writeln("			<div id=\"footer-top-two\">");
document.writeln("				<h5>Guiding Authority</h5>");
document.writeln("				<p>Economy and Information Technology Commission of Shanghai Municipality</p>");
document.writeln("");
document.writeln("				<h5>Organizers</h5>");
document.writeln("				<p>Economy and Information Technology Commission of Shanghai Pudong New Area</p>");
document.writeln("				<p>Jinqiao Bureau of China (Shanghai) Pilot Free Trade Zone Administration</p>");
document.writeln("				<p>Shanghai Jinqiao Economic and Technological Development Administration Committee</p>");
document.writeln("				<p>China Europe International Business School E-platform</p>");
document.writeln("				<p>Shanghai Jinqiao Export Processing Zone Development Co., Ltd.</p>");
document.writeln("				<p>Migu Video Technology Co., Ltd.</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">Sponsors</h5>");
document.writeln("				<p>Shanghai Digital Content Industry Promotion Center</p>");
document.writeln("				<p>Shanghai Xuanjing Science and Technology Development Co., Ltd.</p>");
document.writeln("				<p>Loyal Valley Innovation Capital </p>");
document.writeln("				<p>Beijing VR Times Technology Co., Ltd. (Ling VR)</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">Co-Sponsors</h5>");
document.writeln("				<p>Shanghai Network Audio-visual Association </p>");
document.writeln("				<p>CNR Mobile (Shanghai) Co., Ltd. </p>");
document.writeln("				<p>Yisheng Network Technology (Shanghai) Co., Ltd.</p>");
document.writeln("				<p>Ningbo GQY Video & Telecom Joint Stock Co., Ltd.</p>");
document.writeln("				<p>Shanghai Northern Suburb Future Industry Park Investment, Development and Operation Co., Ltd.</p>");
document.writeln("				<p>Shanghai V-Linker Space Operation and Management Co., Ltd.</p>");
document.writeln("				<p>Shanghai WonderTEK Software Co., Ltd.</p>");
document.writeln("				<p>Hinfu Investment Management Co., Ltd. </p>");
document.writeln("				<p>Shanghai Spaceyun Business Management Co., Ltd. </p>");
document.writeln("				<p>Kuan Capital</p>");
document.writeln("				<p>Macrograph</p>");
document.writeln("				<p>Bomb Entertainment Cultural Media (Beijing) Co., Ltd. </p>");
document.writeln("				<p>Shinect Startup Community & Accelerator </p>");
document.writeln("				<p>Lily Lisa Hollywood LLC </p>");
document.writeln("			</div>");
document.writeln("			<div id=\"footer-top-three\">");
document.writeln("				<h5>Designated Exhibitor</h5>");
document.writeln("				<p>Shanghai Taopu Cultural Development Co., Ltd.</p>");
document.writeln("				<P>Vanguard Design LLC</P>");
document.writeln("				<P>Construction Exception Cultural Development LLC</P>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">Designated Advertising Partners</h5>");
document.writeln("				<p>Migu Live Show  Ltd</p>");
document.writeln("				<p>Beijing Monister Technology Co.</p>");
document.writeln("				<p>Magical World (Beijing) Network Technology Co., Ltd., </p>");
document.writeln("				<p>www.vrjie.com</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">Designated Registration Platform</h5>");
document.writeln("				<p>yoopay.cn </p>");
document.writeln("				");
document.writeln("				<h5 style=\"margin-top:30px\">Designated Legal Advisor</h5>");
document.writeln("				<p> Shanghai CENLAW & PARINERS</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">Designated Translation Partner</h5>");
document.writeln("				<p>Glossa Language Technologies Co., Ltd.</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">Media</h5>");
document.writeln("				<p>China News Service, China Network Television, Sina, Tencent, Sohu, Youku Tudou, IQIYI, etc </p>");
document.writeln("			</div>");
document.writeln("			<div class=\"clear\"></div>");
document.writeln("		</div>");
document.writeln("		<div id=\"footer-bottom\">");
document.writeln("			<div id=\"footer-bottom-one\">");
document.writeln("				<span><a href=\"sign-up.html\">Register</span></a>");
document.writeln("				<span id=\"line-one\">|</span>");
document.writeln("				<span><a href=\"agenda.html\">Schedule</span></a>");
document.writeln("				<span id=\"line-two\">|</span>");
document.writeln("				<span><a href=\"meeting.html\">Guidance</span></a>");
document.writeln("			</div>");
document.writeln("			<div id=\"footer-bottom-two\">");
document.writeln("				<p>Global Virtual Reality Conference Committee</p>");
document.writeln("				<p>Contact：James Zhao</p>");
document.writeln("				<p>18710037231&nbsp;jameszhao@gvrc.org.cn</p>");
document.writeln("			</div>");
document.writeln("			<div id=\"footer-bottom-three\">");
document.writeln("				<p>Address：2607 N.28 Jinqiao Rd, Pudong New district, Shanghai</p>");
document.writeln("				<p>Post Code：201206</p>");
document.writeln("				<p>Phone：021-50187907</p>");
document.writeln("			</div>");
document.writeln("			<div class=\"clear\"></div>");
document.writeln("		</div>");
document.writeln("		<div class=\"icp\">");
document.writeln("			<span>京ICP备14038822号-4");
document.writeln("</span>");
document.writeln("		</div>");
document.writeln("	</footer>");
document.writeln("	<div id=\"return-top\" class=\"return-top\"></div>");
document.writeln("	<div id=\"weixin\">");
document.writeln("		<div class=\"erweima\">");
document.writeln("			");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</body>");
document.writeln("<script src=\"../js/jquery2.2.0.js\"></script>");
document.writeln("<script src=\"../js/index.js\"></script>");
document.writeln("</html>");