document.writeln("<!doctype html>");
document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("	<meta charset=\"UTF-8\">");
document.writeln("	<meta name=\"viewport\" content=\"initial-scale=1.0, maximum-scale=1.0, user-scalable=no\"/>");
document.writeln("	<title>Footer</title>");
document.writeln("	<link rel=\"stylesheet\" href=\"./css/index.css\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div id=\"myfooter\">");
document.writeln("	<div id=\"bottom-banner\" class=\"bottom-banner\">");
document.writeln("	</div>");
document.writeln("	");
document.writeln("	<footer id=\"footer\">");
document.writeln("		<div id=\"footer-top\">");
document.writeln("			<div id=\"footer-top-logoo\">");
document.writeln("				<a href=\"index.html\"><img src=\"./images/newlogo.png\" alt=\"\"></a>");
document.writeln("				<ul>");
document.writeln("					<li><a href=\"\"><img src=\"./images/wachat2new.png\" alt=\"\"></a></li>");
document.writeln("					<li><a href=\"https://twitter.com/GvrcJameszhao\"><img src=\"./images/twwiter2.png\" alt=\"\"></a></li>");
document.writeln("					<li><a href=\"https://www.facebook.com/gvrcshanghai/\"><img src=\"./images/facebook-hover.png\" alt=\"\"></a></li>");
document.writeln("				</ul>");
document.writeln("				<span></span>");
document.writeln("			</div>");
document.writeln("			<div id=\"footer-top-two\">");
document.writeln("				<h5>指导单位</h5>");
document.writeln("				<p>上海市经济和信息化委员会</p>");
document.writeln("");
document.writeln("				<h5>主办单位</h5>");
document.writeln("				<p>上海市浦东新区经济和信息化委员会</p>");
document.writeln("				<p>中国（上海）自由贸易试验区管理委员会金桥管理局</p>");
document.writeln("				<p>上海金桥经济技术开发管理委员会</p>");
document.writeln("				<p>中欧国际工商学院众创平台</p>");
document.writeln("				<p>上海金桥出口加工区开发股份有限公司</p>");
document.writeln("				<p>中国移动咪咕视讯科技有限公司</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">承办单位</h5>");
document.writeln("				<p>上海市数字内容产业促进中心</p>");
document.writeln("				<p>上海绚景科技发展有限公司</p>");
document.writeln("				<p>正心谷创新资本 </p>");
document.writeln("				<p>北京维阿时代科技有限公司（灵镜科技）</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">协办单位</h5>");
document.writeln("				<p>上海市网络视听行业协会 </p>");
document.writeln("				<p>央广视讯传媒（上海）有限公司 </p>");
document.writeln("				<p>一声网络科技（上海）有限公司</p>");
document.writeln("				<p>宁波GQY视讯股份有限公司</p>");
document.writeln("				<p>上海北郊未来产业园投资开发营运有限公司</p>");
document.writeln("				<p>上海宝山工业园区管理委员会</p>");
document.writeln("				<p>上海微领地创客空间运营管理股份有限公司</p>");
document.writeln("				<p>上海网达软件股份有限公司 </p>");
document.writeln("				<p>兴富投资管理有限公司 </p>");
document.writeln("				<p>上海云孟企业管理有限公司（云享客）</p>");
document.writeln("				<p>宽资本</p>");
document.writeln("				<p>Macrograph</p>");
document.writeln("				<p>爆娱文化传媒（北京）有限公司</p>");
document.writeln("				<p>硅谷巷内创业社区&加速器 </p>");
document.writeln("				<p>Lily Lisa Hollywood LLC </p>");
document.writeln("			</div>");
document.writeln("			<div id=\"footer-top-three\">");
document.writeln("				<h5>指定策展单位</h5>");
document.writeln("				<p>上海韬朴文化发展有限公司 </p>");
document.writeln("				<p>万邦智合设计有限公司</p>");
document.writeln("				<p>建筑之外文化投资发展有限公司</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">指定宣传合作</h5>");
document.writeln("				<p>咪咕直播</p>");
document.writeln("				<p>北京友信通联科技有限公司</p>");
document.writeln("				<p>幻维世界（北京）网络科技有限公司</p>");
document.writeln("				<p>VR界网</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">指定注册平台</h5>");
document.writeln("				<p>友付</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">指定翻译</h5>");
document.writeln("				<p>北京格罗萨技术交流有限公司</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">指定法律顾问</h5>");
document.writeln("				<p>上海浦瑞律师事务所</p>");
document.writeln("");
document.writeln("				<h5 style=\"margin-top:30px\">支持媒体</h5>");
document.writeln("				<p>中新社、中国网络电视台、新浪网、腾讯网、搜狐网、优酷土豆、爱奇艺等 </p>");
document.writeln("			</div>");
document.writeln("			<div class=\"clear\"></div>");
document.writeln("		</div>");
document.writeln("		<div id=\"footer-bottom\">");
document.writeln("			<div id=\"footer-bottom-one\">");
document.writeln("				<span><a href=\"sign-up.html\">参会报名</span></a>");
document.writeln("				<span id=\"line-one\">|</span>");
document.writeln("				<span><a href=\"agenda.html\">大会议程</span></a>");
document.writeln("				<span id=\"line-two\">|</span>");
document.writeln("				<span><a href=\"meeting.html\">会务指南</span></a>");
document.writeln("			</div>");
document.writeln("			<div id=\"footer-bottom-two\">");
document.writeln("				<p>全球虚拟现实大会组织委员会</p>");
document.writeln("				<p>联系人：胡&nbsp;婕</p>");
document.writeln("				<p>18301913659&nbsp;huj@chinadcic.org.cn</p>");
document.writeln("			</div>");
document.writeln("			<div id=\"footer-bottom-three\">");
document.writeln("				<p>地址：上海市浦东新区金桥路28号2607</p>");
document.writeln("				<p>邮编：201206</p>");
document.writeln("				<p>电话：021-50187907</p>");
document.writeln("			</div>");
document.writeln("			<div class=\"clear\"></div>");
document.writeln("		</div>");
document.writeln("		<div class=\"icp\">");
document.writeln("			<span>京ICP备14038822号-4</span>");
document.writeln("		</div>");
document.writeln("	</footer>");
document.writeln("	<div id=\"return-top\" class=\"return-top\"></div>");
document.writeln("	<div id=\"weixin\">");
document.writeln("		<div class=\"erweima\">");
document.writeln("			");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("<script src=\"./js/jquery2.2.0.js\"></script>");
document.writeln("<script src=\"./js/index.js\"></script>");
document.writeln("");
document.writeln("</html>");